ARM GAS  /tmp/ccR2gBzJ.s 			page 1


   1              	# 1 "startup/startup_stm32f103c8.S"
   1              	...
   1              	...
   0              	
   0              	
ARM GAS  /tmp/ccR2gBzJ.s 			page 2


DEFINED SYMBOLS
startup/startup_stm32f103c8.S:124    .isr_vector:00000000 g_pfnVectors
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 Default_Handler
startup/startup_stm32f103c8.S:51     *ABS*:f108f85f BootRAM
startup/startup_stm32f103c8.S:64     .text.Reset_Handler:00000000 Reset_Handler
startup/startup_stm32f103c8.S:67     .text.Reset_Handler:00000000 $t
startup/startup_stm32f103c8.S:76     .text.Reset_Handler:0000000c LoopCopyDataInit
startup/startup_stm32f103c8.S:70     .text.Reset_Handler:00000004 CopyDataInit
startup/startup_stm32f103c8.S:89     .text.Reset_Handler:00000020 LoopFillZerobss
startup/startup_stm32f103c8.S:85     .text.Reset_Handler:0000001a FillZerobss
startup/startup_stm32f103c8.S:109    .text.Default_Handler:00000000 Infinite_Loop
startup/startup_stm32f103c8.S:110    .text.Default_Handler:00000000 $t
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 NMI_Handler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 HardFault_Handler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 MemManage_Handler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 BusFault_Handler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 UsageFault_Handler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 SVC_Handler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 DebugMon_Handler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 PendSV_Handler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 SysTick_Handler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 WWDG_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 PVD_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 TAMPER_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 RTC_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 FLASH_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 RCC_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 EXTI0_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 EXTI1_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 EXTI2_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 EXTI3_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 EXTI4_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 DMA1_Channel1_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 DMA1_Channel2_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 DMA1_Channel3_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 DMA1_Channel4_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 DMA1_Channel5_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 DMA1_Channel6_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 DMA1_Channel7_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 ADC1_2_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 USB_HP_CAN1_TX_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 USB_LP_CAN1_RX0_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 CAN1_RX1_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 CAN1_SCE_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 EXTI9_5_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 TIM1_BRK_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 TIM1_UP_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 TIM1_TRG_COM_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 TIM1_CC_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 TIM2_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 TIM3_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 TIM4_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 I2C1_EV_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 I2C1_ER_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 I2C2_EV_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 I2C2_ER_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 SPI1_IRQHandler
ARM GAS  /tmp/ccR2gBzJ.s 			page 3


startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 SPI2_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 USART1_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 USART2_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 USART3_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 EXTI15_10_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 RTCAlarm_IRQHandler
startup/startup_stm32f103c8.S:108    .text.Default_Handler:00000000 USBWakeUp_IRQHandler
startup/startup_stm32f103c8.S:107    .text.Reset_Handler:00000030 $d
                   .debug_aranges:0000000c $d

UNDEFINED SYMBOLS
_sidata
_sdata
_edata
_sbss
_ebss
SystemInit
main
_estack
